name:                scratch-bit
version:             0.1.0.0
github:              "githubuser/scratch-bit"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/scratch-bit#readme>

dependencies:
- base >= 4.7 && < 5
- time
- cryptohash-sha256 == 0.11.101.0 
- bytestring
- crypto-pubkey
- crypto-pubkey-types
- binary
- crypto-random
- crypto-api
- crypto-numbers
  # - cryptonite

library:
  source-dirs: src

executables:
  scratch-bit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scratch-bit

tests:
  scratch-bit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scratch-bit
